### ISSUE TITLE
Lock screen theme needs update for Plasma 5.25

### ISSUE THREAD

**Issue by renyuneyun** [varlesh/nova-kde#3]
Hi. Thanks for the nice theme.

Unfortunately, the lock screen theme no longer work for Plasma 5.25. Other parts still work fine.

As reflected from https://bugs.kde.org/show_bug.cgi?id=455639#c1, Plasma 5.25 has updated the lock screen API. (Maybe for supporting sleep and hibernate?)

**Comment by varlesh** [comment]
Yes, new API not compability with old Plasma LockScreens...
BUT more distros used old Plasma version or LTS and i don't know how better doing this...
I'm port Pengi version for Plasma 5.25 (with minimal changes, if possible) you can test it

**Comment by varlesh** [comment]
https://github.com/varlesh/nova-kde/commit/85580632bd7e09e3514cbe1b235ccfffb0ad9e3b

**Comment by varlesh** [comment]
Updated Pengi version upload on KDE Store.... Another variant will be updated too

**Comment by renyuneyun** [comment]
Thanks very much! Sorry I was busy earlier and did not have time to test. The current version (on pling) works without issues.

**Comment by renyuneyun** [comment]
> BUT more distros used old Plasma version or LTS and i don't know how better doing this...

<del>Maybe you could have two files (for each theme varient) on pling / kde store, with names differentiating plasma version.
One day, maybe remove the old one when most distros moved to 5.25?
For source maintenance, git has the capability.</del>

Seems you are already doing this :) Interesting that Discover automatically installs *a* version for me, and that is the correct one. Interesting behaviour.

A side comment: maybe better name for the package files? As a user, the file names for many packages often made me confused...

**Comment by varlesh** [comment]
Discover does not support multiloading, but downloads and updates the topmost file. Users of the old Plasma will have to update manually. I only left the option to use the theme in all versions of Plasma, as far as possible.
